### ISSUE TITLE
Is there any future plan for Master/Doctor thesis?

### ISSUE THREAD

**Issue by NewtonVan** [smallscientist1/ustcthss-typst#1]
I really appreciate your brilliant job in the repo. And I want to know is it possible to create a template for Master/Doctor thesis?

**Comment by smallscientist1** [comment]
Thanks for your appreciation! Currently, there is no plan to support Master/Doctor thesis myself, but any PR about Master/Doctor thesis is very welcomed. We can implement it as an option in `template.typ` for users to choose whether it is an undergraduate thesis, a master's thesis or a Doctor thesis.
